### ISSUE TITLE
Plotting errors in NaVis

### ISSUE THREAD

**Issue by SridharJagannathan** [schlegelp/navis#2]
I have noticed two plotting errors in Navis:
The full code to reproduce the problem is here: https://github.com/flyconnectome/2020hemibrain_ALLN/blob/fba561dbb0a0ebe4b63c885c831dc65f9d902b0a/Python/HemibrainPN_kde.ipynb

1) When connectors are plotted in 3-d plot like `fig = navis.plot3d([pn_skeletons[0], al],connectors=True)` refer to cell#48
![newplot (5)](https://user-images.githubusercontent.com/13106358/78006153-8714c380-7334-11ea-90b7-4116730737d9.png)

2) When connectors are only plotted for a particular neuron, they are in the wrong orientation(location), please refer to cell#26, I have cross verified by plotting only the connectors (synapeses) where they are in correct location, but however when using `navis.plot2d([to_plot_pr, al], connectors=True, connectors_only=True, ax=ax,
              color=[sns.color_palette('muted', 4)[0], (.8, .8, .8, .2)],
              method='3d', lw=.8)` they are plotted incorrectly.

**Comment by schlegelp** [comment]
Re 1: Good catch. Fixed with 7bd3cde06cacdcb459ae2fcbc3b449bc88b9086f

Re 2: I have yet to rerun your example but it looks to me that the neuron(s) in the top row are simply different from those in the mid/bottom row. I suspect there is something wrong with how you subset the neuronlist. Could you check what's contained in the `to_plot_pr` NeuronList?

<img width="303" alt="Screenshot 2020-03-31 at 10 13 14" src="https://user-images.githubusercontent.com/7161148/78008972-4159fa00-7338-11ea-886b-f5a101098bd0.png">

**Comment by SridharJagannathan** [comment]
@schlegelp You are right reg 2) I made a mistake with the indexes fixed it now and the correct results are indeed displayed here: https://github.com/flyconnectome/2020hemibrain_ALLN/blob/53547a848d88fa544180929a123637e4a2ffcaea/Python/HemibrainPN_kde.ipynb
