### ISSUE TITLE
use of dict mapping on navis.plot3d

### ISSUE THREAD

**Issue by Gigi-prisco** [schlegelp/navis#37]
I am trying to plot a 3d skeleton of a neuron of interest (nl) where only the connectors to/from another neuron of choice (APL) are visualized. I have tried the following code but i still get all connectors with the std red/blue code for output/input synapses. What am I doing wrong?

ca = neu.fetch_roi('CA(R)')
nl = neu.fetch_skeletons(5813069089)
navis.plot3d([ca, nl], connectors = True, cn_colors = {'APL': (0,0,0)})

<img width="726" alt="Screenshot 2021-04-22 at 15 03 18" src="https://user-images.githubusercontent.com/72209449/115718914-e1d3ef80-a37b-11eb-8ced-fc4856141452.png">

**Comment by schlegelp** [comment]
Afraid this is not how the `cn_color` parameter works. From `help(navis.plot3d)`:

```Python
cn_colors :       str | tuple | dict | "neuron"
                  Overrides the default colors:

                  - single color as str (e.g. ``'red'``) or rgb tuple (e.g.
                    ``(1, 0, 0)``)
                  - dict mapping the connectors tables ``type`` column to a
                    color (e.g. `{0: (1, 0, 0)}`)
                  - with "neuron", connectors will receive the same color as
                    their neuron
```

Bottom line: `cn_dict` lets you choose whether you want e.g. presynapses in green instead of red. I will update the help to make this clearer. 

For what you want to do there are two options:

1. Subset the connectors table in `nl` to only those synapses from/to the APL. This is a bit tricky with neuprint IIRC. 
2. Fetch the synapses between APL and your neuron separately and add them as a scatter plot

An illustrative example for option 2: 

Here I'm visuazing inputs from APL (425790257) onto LHMB1 (5813020988)
```Python
>>> # Fetch LHMB1
>>> nl = neu.fetch_skeletons(5813020988, with_synapses=True)
>>> # Fetch connections from APL onto LHMB1
>>> cn = neu.fetch_synapse_connections(source_criteria=neu.NeuronCriteria(bodyId=425790257), target_criteria=neu.NeuronCriteria(bodyId=5813020988))
>>> # Subset to those in the CA 
>>> cn = cn[cn.roi_post == 'CA(R)']
>>> # Get the xyz locations 
>>> locs = cn[['x_post', 'y_post', 'z_post']].values
>>> # Plot 
>>> navis.plot3d([nl, locs, ca], scatter_kws={'color': 'green', 'size': 5}, color='k')
```

<img width="762" alt="Screenshot 2021-04-22 at 14 18 54" src="https://user-images.githubusercontent.com/7161148/115721176-b3531600-a375-11eb-9848-405de6963682.png">

**Comment by Gigi-prisco** [comment]
Understood, and I have managed to get the plot I was looking for. Just one further issue, the `color='k'` piece makes both my neuron and the calyx roi black. How can I change the color of the skeleton while keeping the roi in its typical light grey.

Thank you very much for your help

**Comment by schlegelp** [comment]
Hmm... It shouldn't do that. What version of navis are you using?

**Comment by schlegelp** [comment]
Try updating: the most recent version is `0.5.3`.

```bash
pip3 install navis -U
```

Also what browser are you using? I had some issue with plotly plots in Safari in the past.

**Comment by schlegelp** [comment]
Also note that you will have to restart the Python kernel in your notebook and re-run your code for the update to take effect.

**Comment by Gigi-prisco** [comment]
It worked! Once again, thank you!
One last question. Would all this work on a mesh instead of a skeleton? If yes, can I just substitute `neu.fetch_skeletons` with `neu.fetch_mesh_neuron` to do that?

**Comment by schlegelp** [comment]
@Gigi-prisco can this issue be closed?
